<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>中育ToolBox</AssemblyName>
    <RootNamespace>ZytbSiteHost</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <InvariantGlobalization>false</InvariantGlobalization>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <SelfContained Condition="'$(SelfContained)' == ''">true</SelfContained>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="app.ico" Condition="Exists('app.ico')" />
  </ItemGroup>
</Project>
